### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by vinitraj10** [Groww/frontatish#44]
Writing simple and meaningful documentation for setting up and contributing to this repo.

**Comment by priyanshu0405** [comment]
hey @vinitraj10, can I take this issue? Thanks!!

**Comment by vinitraj10** [comment]
Hey @priyanshu0405 , Glad you are willing to contribute in this project, You can take any of the open issue, not a problem, also would like to let you know that this is an experimental project by Groww Dev team, so will be very happy to hear any bug, issue or any suggestion if you have.

**Comment by priyanshu0405** [comment]
Hey @vinitraj10, do you want me to add "How to contribute" to README.md or write CONTRIBUTING.md  in simpler language?

**Comment by vinitraj10** [comment]
Hey @priyanshu0405, I think moving to README.md would be great for now, if you could provide that info clearly that will be really great for others devs to kickoff their development in this project
